#!/usr/bin/env bash
# Shared helpers for scripts/test-plan-tracking/. Sourced by run.sh
# and every lib/<phase>.sh entrypoint.

set -euo pipefail

DRIVER_ROOT="${DRIVER_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
# Testbed selection. Defaults to the GitHub testbed. To run against another
# provider, point both at a checkout of that provider's testbed — e.g. a
# self-hosted GitLab project:
#   TESTBED_ROOT=$HOME/Project/graysurf/plan-tracking-testbed-gitlab \
#   TESTBED_REPO=terrylin/plan-tracking-testbed-gitlab \
#     bash scripts/test-plan-tracking/run.sh setup happy-path
# The provider/host are detected from TESTBED_ROOT's git remote (see tb_forge).
TESTBED_ROOT="${TESTBED_ROOT:-${HOME}/Project/graysurf/plan-tracking-testbed}"
TESTBED_REPO="${TESTBED_REPO:-graysurf/plan-tracking-testbed}"
STATE_DIR="${DRIVER_ROOT}/.state"
STATE_FILE="${STATE_DIR}/current-run.env"

mkdir -p "${STATE_DIR}"

log() {
  printf '[test-plan-tracking] %s\n' "$*" >&2
}

die() {
  printf '[test-plan-tracking] FATAL: %s\n' "$*" >&2
  exit 1
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 ||
    die "missing required command: $1"
}

load_fixture() {
  local name="${1:?fixture name required}"
  FIXTURE_ROOT="${DRIVER_ROOT}/fixtures/${name}"
  [ -d "${FIXTURE_ROOT}" ] ||
    die "unknown fixture: ${name} (looked under ${FIXTURE_ROOT})"
  # shellcheck disable=SC1091
  . "${FIXTURE_ROOT}/manifest.sh"
}

state_save() {
  # Persist key=value pairs across phases. Values are single-quoted so
  # values containing spaces or shell metacharacters survive sourcing.
  {
    printf '# generated by run.sh — do not edit by hand\n'
    for kv in "$@"; do
      local key="${kv%%=*}"
      local val="${kv#*=}"
      # escape embedded single quotes as '\''
      local escaped="${val//\'/\'\\\'\'}"
      printf "%s='%s'\n" "${key}" "${escaped}"
    done
  } >"${STATE_FILE}"
}

state_load() {
  [ -f "${STATE_FILE}" ] ||
    die "no current run state at ${STATE_FILE} — run 'setup' first"
  # shellcheck disable=SC1090
  . "${STATE_FILE}"
}

state_update() {
  # Append/replace a single key=value in the state file. Quoted to
  # survive sourcing across phases.
  local key="${1%%=*}"
  local val="${1#*=}"
  local escaped="${val//\'/\'\\\'\'}"
  if [ -f "${STATE_FILE}" ]; then
    grep -v "^${key}=" "${STATE_FILE}" >"${STATE_FILE}.tmp" || true
    mv "${STATE_FILE}.tmp" "${STATE_FILE}"
  fi
  printf "%s='%s'\n" "${key}" "${escaped}" >>"${STATE_FILE}"
}

testbed_git() {
  git -C "${TESTBED_ROOT}" "$@"
}

testbed_run() {
  (cd "${TESTBED_ROOT}" && "$@")
}

# ---- Provider seam ----------------------------------------------------
# The driver inspects provider state through `forge-cli` (issues / PRs) and
# plain `git` (branch ops), never `gh` directly, so it runs against GitHub
# or GitLab unchanged. Each helper normalizes forge-cli's v1 envelope
# (snake_case fields, lowercase state) back into the gh-shaped JSON the
# call sites historically consumed — so the phase logic in assert.sh /
# teardown.sh / status.sh stays provider-agnostic and barely changes.
#
# Provider selection is implicit: point TESTBED_ROOT + TESTBED_REPO at any
# provider's checkout (a GitHub clone or a self-hosted GitLab clone) and the
# driver follows it. `tb_forge` runs forge-cli from inside TESTBED_ROOT so the
# provider AND host are detected from the testbed's own git remote. We
# deliberately do NOT pass `--provider`: forge-cli's forced-provider path pins
# the host to the provider default (`gitlab.com`), which would miss a
# self-hosted instance such as `gitlab.<corp>.com`. Detection from the remote
# resolves both correctly. TESTBED_ROOT is the single source of truth (git
# branch ops already run there via testbed_git), so TESTBED_REPO must name the
# same project.
tb_forge() {
  (cd "${TESTBED_ROOT}" && forge-cli "$@")
}

# Echo the number of the newest issue whose title exactly matches $1, or
# empty. forge-cli has no server-side title search, so filter the full
# issue list client-side.
tb_issue_find_by_title() {
  local title="$1"
  tb_forge issue list --repo "${TESTBED_REPO}" --state all --format json |
    jq -r --arg t "${title}" \
      '[.data.items[] | select(.title == $t) | .number] | sort | reverse | .[0] // empty'
}

# Write a gh-shaped snapshot of issue $1 to file $2:
#   {number,title,state(UPPER),labels:[{name}],body,comments:[{body,...}]}
# State is upper-cased and labels re-objectified so existing call-site jq
# (`.state == "OPEN"`, `.labels[].name`, `.comments[].body`) is unchanged.
tb_issue_snapshot() {
  local number="$1" out="$2"
  # --with-comments: forge-cli omits the comment stream otherwise (returns an
  # empty array), and the phase checks count role markers across comments.
  tb_forge issue view "${number}" --repo "${TESTBED_REPO}" --with-comments --format json |
    jq '.data | {
      number, title,
      state: (.state | ascii_upcase),
      labels: [.labels[] | {name: .}],
      body,
      comments: [.comments[] | {body, url, author, created_at}]
    }' >"${out}"
}

# Echo gh-shaped JSON for the newest PR on head branch $1, or empty:
#   {number,state(UPPER),mergeCommit:{oid}}
# `pr list` omits the merge SHA, so resolve the number by head, then
# `pr view` for state + merge_commit_sha.
tb_pr_resolve_by_head() {
  local head="$1" number
  number=$(tb_forge pr list --repo "${TESTBED_REPO}" --head "${head}" --state all --format json |
    jq -r '[.data.items[].number] | sort | reverse | .[0] // empty')
  [ -z "${number}" ] && return 0
  tb_forge pr view "${number}" --repo "${TESTBED_REPO}" --format json |
    jq '.data | {
      number,
      state: (.state | ascii_upcase),
      mergeCommit: { oid: (.merge_commit_sha // "") }
    }'
}

# Echo, one per line, the numbers of OPEN issues that do NOT carry the
# durable `plan-issue-finding` label (those trackers must survive teardown).
tb_open_issues_except_finding() {
  tb_forge issue list --repo "${TESTBED_REPO}" --state open --format json |
    jq -r '.data.items[] | select((.labels | index("plan-issue-finding")) | not) | .number'
}

# Comment (optional $2) then close issue $1. forge-cli has no close-reason
# flag; GitHub's "not planned" reason is dropped (cosmetic for teardown).
tb_issue_close() {
  local number="$1" comment="${2:-}"
  if [ -n "${comment}" ]; then
    tb_forge issue comment "${number}" --repo "${TESTBED_REPO}" --body "${comment}" >/dev/null
  fi
  tb_forge issue close "${number}" --repo "${TESTBED_REPO}" >/dev/null
}

# Echo, one per line, every remote branch name. git-native — no provider API.
tb_remote_branches() {
  testbed_git ls-remote --heads origin |
    sed -E 's#^[0-9a-f]+[[:space:]]+refs/heads/##'
}

# Delete a remote branch. git-native.
tb_remote_branch_delete() {
  testbed_git push origin --delete "$1"
}

# Provenance + CLI-floor helpers (finding #19). Sourced last so every phase
# entrypoint that sources common.sh also gets stamp_provenance / assert_cli_floor.
# shellcheck disable=SC1091
. "${DRIVER_ROOT}/lib/provenance.sh"
