#!/usr/bin/env bash
# Shared helpers for scripts/test-plan-tracking/. Sourced by run.sh
# and every lib/<phase>.sh entrypoint.

set -euo pipefail

DRIVER_ROOT="${DRIVER_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
TESTBED_ROOT="${TESTBED_ROOT:-${HOME}/Project/graysurf/plan-tracking-testbed}"
TESTBED_REPO="${TESTBED_REPO:-graysurf/plan-tracking-testbed}"
STATE_DIR="${DRIVER_ROOT}/.state"
STATE_FILE="${STATE_DIR}/current-run.env"

mkdir -p "${STATE_DIR}"

log() {
  printf '[test-plan-tracking] %s\n' "$*" >&2
}

die() {
  printf '[test-plan-tracking] FATAL: %s\n' "$*" >&2
  exit 1
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 ||
    die "missing required command: $1"
}

load_fixture() {
  local name="${1:?fixture name required}"
  FIXTURE_ROOT="${DRIVER_ROOT}/fixtures/${name}"
  [ -d "${FIXTURE_ROOT}" ] ||
    die "unknown fixture: ${name} (looked under ${FIXTURE_ROOT})"
  # shellcheck disable=SC1091
  . "${FIXTURE_ROOT}/manifest.sh"
}

state_save() {
  # Persist key=value pairs across phases. Values are single-quoted so
  # values containing spaces or shell metacharacters survive sourcing.
  {
    printf '# generated by run.sh — do not edit by hand\n'
    for kv in "$@"; do
      local key="${kv%%=*}"
      local val="${kv#*=}"
      # escape embedded single quotes as '\''
      local escaped="${val//\'/\'\\\'\'}"
      printf "%s='%s'\n" "${key}" "${escaped}"
    done
  } >"${STATE_FILE}"
}

state_load() {
  [ -f "${STATE_FILE}" ] ||
    die "no current run state at ${STATE_FILE} — run 'setup' first"
  # shellcheck disable=SC1090
  . "${STATE_FILE}"
}

state_update() {
  # Append/replace a single key=value in the state file. Quoted to
  # survive sourcing across phases.
  local key="${1%%=*}"
  local val="${1#*=}"
  local escaped="${val//\'/\'\\\'\'}"
  if [ -f "${STATE_FILE}" ]; then
    grep -v "^${key}=" "${STATE_FILE}" >"${STATE_FILE}.tmp" || true
    mv "${STATE_FILE}.tmp" "${STATE_FILE}"
  fi
  printf "%s='%s'\n" "${key}" "${escaped}" >>"${STATE_FILE}"
}

testbed_git() {
  git -C "${TESTBED_ROOT}" "$@"
}

testbed_run() {
  (cd "${TESTBED_ROOT}" && "$@")
}

# Provenance + CLI-floor helpers (finding #19). Sourced last so every phase
# entrypoint that sources common.sh also gets stamp_provenance / assert_cli_floor.
# shellcheck disable=SC1091
. "${DRIVER_ROOT}/lib/provenance.sh"
